version: '3.1'
services:
  python-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/home
    environment:
      FLASK_APP: "application"
      FLASK_ENV: "development"
      FLASK_DEBUG: 1
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
