# Generated by Django 2.2 on 2019-04-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_auto_20190420_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=64)),
                ('lname', models.CharField(max_length=64)),
                ('trains', models.ManyToManyField(blank=True, related_name='passengers', to='train.Train')),
            ],
        ),
    ]
